### ISSUE TITLE
Spread operator doesn't work

### ISSUE THREAD

**Issue by delacruz-dev** [esdoc/esdoc-es7-plugin#3]
Hi!

I'm using esdoc to document my code and the esdoc-es7-plugin. I've got the following code in one of my functions:

``` javascript
return new SomeEntity({
      ...someParams,
      some,
      other,
      params
    });
```

And I'm getting the following error on generating the documentation:

```
error: could not parse the following code. if you want to use ES7, see esdoc-es7-plugin(https://github.com/esdoc/esdoc-es7-plugin)
```

This is my `esdoc.json`

``` json
{
  "source": "./src",
  "destination": "./docs",
  "coverage": true,
  "plugins": [
    {"name": "esdoc-es7-plugin"}
  ],
  "test": {
    "type": "mocha",
    "source": "./test",
    "includes": ["Spec\\.js$"]
  }
}
```

What am I doing bad? It doesn't happen when compiling with babel, so I guess the mistake is not in my code :(

**Comment by h13i32maru** [comment]
@danderu Hi! Thanks for this issue!
Your code is valid. This is ESDoc bug. I will fix this issue in next version.

For now, can use the following workaround:

```
cd /usr/local/lib/node_modules/esdoc-es7-plugin/
rm -rf node_modules/estraverse
npm i estraverse@4.1.0
```

**Comment by h13i32maru** [comment]
@danderu I published v0.0.3. The version fixed this issue.

**Comment by delacruz-dev** [comment]
Thanks for the quick fix!

**Comment by h13i32maru** [comment]
I published ESDoc v0.4.3. This plugin require the ESDoc version. Please update ESDoc as well.

**Comment by delacruz-dev** [comment]
Sorry, but I'm still having this issue after upgrading to v0.4.3 and plugin version 0.0.3. I applied the same workaround and it works.

```
cd /usr/local/lib/node_modules/esdoc-es7-plugin/
rm -rf node_modules/estraverse
npm i estraverse@4.1.0
```

**Comment by parris** [comment]
hmmm, I'm still seeing this issue. I tried manually installing estraverse too.

**Comment by parris** [comment]
code:

```
{ SyntaxError: unknown: Unexpected token (14:8)
  12 | export const store = createStore(
  13 |     combineReducers({
> 14 |         ...reducers,
     |         ^
  15 |         routing: routerReducer,
  16 |     })
  17 | )
```

**Comment by SamMatthewsIsACommonName** [comment]
Hi I'm also having this issue:
`{ SyntaxError: unknown: Unexpected token (61:15)
  59 |   switch (action.type) {
  60 |     case 'CLOSE_MENU':
> 61 |       return { ...state, menuOpen: false };
     |                ^
  62 |     case 'UPDATE_SCROLL_LOCATION':
  63 |       return { ...state, scrollLocation: action.scrollLocation };
  64 |     case DISPLAY_SUCCESS_MESSAGE:`

**Comment by hughvidos** [comment]
I'm seeing the same.
```{ SyntaxError: unknown: Unexpected token (22:4)
  20 | export default StyleSheet.create({
  21 |   backButton: {
> 22 |     ...navButton,
     |     ^
  23 |     marginTop: Metrics.baseMargin,
  24 |     marginLeft: Metrics.baseMargin
  25 |   },
```
